version: '3'

services:
  postgres-db-master:
    container_name: postgres-db-master
    image: postgres:alpine
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_PASSWORD=password-master

  postgres-db-replica:
    container_name: postgres-db-replica
    image: postgres:alpine
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_PASSWORD=password-replica

  
